apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- if .Values.ingress.annotations }}
  annotations:
  {{ toYaml .Values.ingress.annotations | indent 4 }}
  {{- end }}
  {{- if .Values.ingress.labels }}
  labels:
  {{ toYaml .Values.ingress.labels | indent 4 }}
  {{- end }}
  name: {{ template "fullname" .}}-socks-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: front-end
            port:
              number: 80
        path: /
        pathType: Prefix
    {{- if .Values.ingress.host }}
    host: {{ .Values.ingress.host }}
    {{- end }}
  {{- if .Values.ingress.tlsSecretName }}
  tls:
  - secretName: {{ .Values.ingress.tlsSecretName }}
    {{- if .Values.ingress.host }}
    hosts:
    - {{ .Values.ingress.host }}
    {{- end }}
  {{- end }}
