{{- if .Values.zipkin.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  labels:
    name: zipkin
spec:
  type: {{ .Values.zipkin.service.type }}
  ports:
  - port: {{ .Values.zipkin.service.port }}
    targetPort: 9411
    protocol: TCP
  selector:
    name: zipkin
{{- end -}}
